import bpy
import csv
import os
import math
import time

# --- CONFIGURATION ---
# Path to the CSV file generated by assign_seville_clusters.py
# Windows paths need double backslashes or raw strings
CSV_PATH = r"e:\Carlos\GitHub\HybridGT\seville_instances.csv"

# Directory containing the OBJ models
MODELS_DIR = r"e:\Carlos\GitHub\HybridGT\obj_models_textured"

# Collection Name
COLLECTION_NAME = "Seville_Buildings"

def import_city():
    print(f"Starting Import from {CSV_PATH}...")
    start_time = time.time()

    # 1. Create Collection
    if COLLECTION_NAME not in bpy.data.collections:
        city_coll = bpy.data.collections.new(COLLECTION_NAME)
        bpy.context.scene.collection.children.link(city_coll)
    else:
        city_coll = bpy.data.collections[COLLECTION_NAME]

    # 2. Read CSV Data
    instances = []
    unique_models = set()
    offset_x = 0
    offset_y = 0
    offset_z = 0
    
    try:
        with open(CSV_PATH, 'r') as f:
            reader = csv.DictReader(f)
            first = True
            for row in reader:
                if first:
                    offset_x = float(row['x'])
                    offset_y = float(row['y'])
                    offset_z = float(row['z'])
                    print(f"Setting Origin to First Building: ({offset_x}, {offset_y}, {offset_z})")
                    first = False
                    
                instances.append(row)
                unique_models.add(row['obj_filename'])
    except FileNotFoundError:
        print(f"Error: CSV file not found at {CSV_PATH}")
        return

    print(f"Found {len(instances)} instances using {len(unique_models)} unique models.")

    # 3. Load Unique Models (Prototypes)
    # We will import them into a hidden collection "Prototypes"
    proto_coll_name = "Prototypes"
    if proto_coll_name not in bpy.data.collections:
        proto_coll = bpy.data.collections.new(proto_coll_name)
        bpy.context.scene.collection.children.link(proto_coll)
        # Hide it
        proto_coll.hide_viewport = True
        proto_coll.hide_render = True
    else:
        proto_coll = bpy.data.collections[proto_coll_name]

    loaded_objects = {} # Map filename -> Blender Object

    for obj_file in unique_models:
        full_path = os.path.join(MODELS_DIR, obj_file)
        if not os.path.exists(full_path):
            print(f"Warning: Model not found: {full_path}")
            continue
            
        # Import OBJ
        # Blender 4.0+ uses bpy.ops.wm.obj_import
        # Blender < 4.0 uses bpy.ops.import_scene.obj
        
        # Try new importer first
        try:
            bpy.ops.wm.obj_import(filepath=full_path, forward_axis='Z', up_axis='Y')
        except AttributeError:
            # Fallback for older Blender
            bpy.ops.import_scene.obj(filepath=full_path, axis_forward='Z', axis_up='Y')
            
        # The imported object is selected
        imported_objs = bpy.context.selected_objects
        
        # Move to prototypes collection
        for obj in imported_objs:
            # Unlink from current collections
            for coll in obj.users_collection:
                coll.objects.unlink(obj)
            # Link to prototypes
            proto_coll.objects.link(obj)
            
            # Store reference (assuming single object per OBJ)
            # The name in Blender might not match filename exactly due to "Building_..." inside OBJ
            loaded_objects[obj_file] = obj
            
            # Ensure origin is at bottom center (0,0,0) - our OBJ generation ensures this relative to geometry
            # But Blender import might offset? Usually OBJ import respects coords.
            
    print(f"Loaded {len(loaded_objects)} unique models.")

    # 4. Create Instances
    # Using Linked Duplicates (Alt+D behavior) for efficiency
    
    count = 0
    for row in instances:
        obj_file = row['obj_filename']
        if obj_file not in loaded_objects:
            continue
            
        proto_obj = loaded_objects[obj_file]
        
        # Create Instance
        instance = proto_obj.copy()
        # Do not copy data (mesh), keeping it linked
        
        # Link to City Collection
        city_coll.objects.link(instance)
        
        # Set Transforms (Relative to First Building)
        x = float(row['x']) - offset_x
        y = float(row['y']) - offset_y
        z = float(row['z']) - offset_z
        angle_deg = float(row['angle_deg'])
        
        instance.location = (x, y, z)
        
        # Rotation
        # Blender rotation_euler is in radians.
        # OBJ was Y-Up, Blender is Z-Up.
        # Our OBJ creation put Height on Y, Depth on Z.
        # When imported with Y-Forward, Z-Up settings (standard), 
        # Blender maps OBJ Y -> Blender Z, OBJ Z -> Blender -Y.
        
        # The 'angle' from shapefile is usually CCW from East (X).
        # We need to rotate around Z axis.
        angle_rad = math.radians(angle_deg)
        instance.rotation_euler[2] = angle_rad
        
        count += 1
        if count % 1000 == 0:
            print(f"Created {count} instances...")

    total_time = time.time() - start_time
    print(f"Finished! Created {count} buildings in {total_time:.2f} seconds.")

if __name__ == "__main__":
    import_city()
